version: '3'

services:
  discover-server:
    build:
      context: ./discovery_server
      dockerfile: Dockerfile

  redevable-service:
    build:
      context: ./RedevableMicroservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discover-server
      - mysql

  categorie-service:
    build:
      context: ./CategorieTerrainMicroservice
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - discover-server
      - mysql

  terrain-service:
    build:
      context: ./TerrainMicroservice
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discover-server
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: project_tnb
      MYSQL_USER: yazoo
      MYSQL_PASSWORD: yazooPassword
      MYSQL_ROOT_PASSWORD: yazooPassword
    ports:
      - "3306:3306"
    # Add any additional configurations for your MySQL service here
